### ISSUE TITLE
Fluent-bit not installed ? / log forwarding not working

### ISSUE THREAD

**Issue by PiotrCzapla** [newrelic/infrastructure-bundle#392]
I can't make the logging work following this [instructions](https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/).
It seems that fluent-bit is not installed. At least I can't run this command after exec bash in the container.

## Description
I'm having a docker container in host mode with infrastructure agent , and I'm trying to make it send all logs from the underlying docker host via mount point /:/host:ro. Unfortunately none of the logs are picked up, the documentation does not mention how to configure the infrastructure bundle in the docker container, but it does mention the tar bar installation that requires fluentbit to be installed manually. I don't see fluent-bit command in the infrastructure container. 

## Expected Behavior
I would expect that the fluent-bit command is installed and log forwarding works just out of the box after coping logging.yml to the /etc/infrastructure/logging.d/

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

The troubleshooting NRDiag does not work in infrastructure-bundle.
### logs of the container
```
newrelic-infra  | time="2024-04-17T14:46:23Z" level=info msg="Creating service..."
newrelic-infra  | time="2024-04-17T14:46:23Z" level=info msg="runtime configuration" agentUser=root component="New Relic Infrastructure Agent" executablePath= maxProcs=1 pluginDir="[/etc/newrelic-infra/integrations.d /var/db/newrelic-infra/integrations.d]"
newrelic-infra  | time="2024-04-17T14:46:23Z" level=info msg="Checking network connectivity..." component=AgentService service=newrelic-infra
newrelic-infra  | time="2024-04-17T14:46:23Z" level=info msg=Initializing component=AgentService elapsedTime=54.101161ms service=newrelic-infra version=1.52.0
newrelic-infra  | time="2024-04-17T14:46:30Z" level=warning msg="unable to initialize containerd client, could be not installed on the host" component=ContainerdSampler error="containerd sampler: containerd error: no active containerd instance found"
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="docker sampler enabled" component=ContainerSampler
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="New Relic infrastructure agent is running." component=AgentService elapsedTime=6.33797666s service=newrelic-infra
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Starting up agent..." component=Agent
newrelic-infra  | time="2024-04-17T14:46:30Z" level=warning msg="failed to connect to DBus. make sure systemd is present." component=NotificationHandler
newrelic-infra  | time="2024-04-17T14:46:30Z" level=warning msg="failed to init shutdown monitor" component=NotificationHandler error="no systemd found"
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Agent plugin" plugin=metadata/attributes
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Agent plugin" plugin=metadata/system
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Agent plugin" plugin=metadata/host_aliases
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Agent plugin" plugin=metadata/agent_config
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Agent plugin" plugin=metadata/proxy_config
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Integration info" arguments="map[extended_innodb_metrics:1 extended_metrics:1 hostname:mysql password:<HIDDEN> port:3306 remote_monitoring:true username:newrelic]" command=status commandLine="[./bin/nri-mysql]" env-vars="map[EXTENDED_INNODB_METRICS:1 EXTENDED_METRICS:1 HOSTNAME:mysql PASSWORD:<HIDDEN> PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PORT:3306 REMOTE_MONITORING:true TEMP_DIR:/tmp/nr-integrations USERNAME:newrelic VERBOSE:0]" instance=mysql-server integration=com.newrelic.mysql interval=30 labels="map[env:production role:write-replica]" os=linux prefix=config/mysql protocolVersion=3 workingDir=/var/db/newrelic-infra/newrelic-integrations
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Integration health check starting" instance=mysql-server integration=com.newrelic.mysql prefix=config/mysql working-dir=/var/db/newrelic-infra/newrelic-integrations
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="Integration health check finished with success" instance=mysql-server integration=com.newrelic.mysql prefix=config/mysql working-dir=/var/db/newrelic-infra/newrelic-integrations
newrelic-infra  | time="2024-04-17T14:46:30Z" level=info msg="connect got id" agent-guid=xxx agent-id=xxx component=IdentityConnectService
newrelic-infra  | time="2024-04-17T14:47:30Z" level=info msg="Integration health check finished with success" component=integrations.runner.Runner integration_name=nri-docker runner_uid=xxxxx
```

### output of the nrdiag
```
gloriosum-jbwww:/# curl https://download.newrelic.com/nrdiag/nrdiag_latest.zip -o nrdiag.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.5M  100 19.5M    0     0  99.6M      0 --:--:-- --:--:-- --:--:--  100M
gloriosum-jbwww:/# unzip nrdiag.zip
Archive:  nrdiag.zip
   creating: nrdiag/
  inflating: nrdiag/README.txt
  inflating: nrdiag/version.txt
   creating: nrdiag/linux/
  inflating: nrdiag/linux/nrdiag_arm64
  inflating: nrdiag/linux/nrdiag_x64
  inflating: nrdiag/LICENSE.txt
   creating: nrdiag/mac/
  inflating: nrdiag/mac/nrdiag_arm64
  inflating: nrdiag/mac/nrdiag_x64
  inflating: nrdiag/LICENSES.json
  inflating: nrdiag/LICENSE
   creating: nrdiag/win/
  inflating: nrdiag/win/nrdiag_x64.exe
  inflating: nrdiag/win/nrdiag_arm64.exe
  inflating: nrdiag/win/nrdiag.exe
gloriosum-jbwww:/# nrdiag/linux/nrdiag_x64

Check Results
-------------------------------------------------
Info     Base/Env/CollectEnvVars [Gathered Environment variables of current shell.]




^C -- I've stopped it after 20 min idle.
```

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Dockerfile
```
FROM newrelic/infrastructure-bundle:3.2.37
RUN echo 'license_key: eulicense' > /etc/newrelic-infra.yml

RUN curl -L https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/nri-mysql_linux_1.10.0_amd64.tar.gz | tar -C / -zx --no-same-owner

ADD ./mysql-config.yml /etc/newrelic-infra/integrations.d/mysql-config.yml
ADD ./logging.yml /etc/newrelic-infra/logging.d/logging.yml
```
logging.yml
```
logs:
  # - name: lsws_access
  #   file: /root/lsws-docker-env/logs/
  #   attributes:
  #     logtype: apache
  - name: lsws_error
    file: /host/root/lsws-docker-env/logs/error.log
    attributes:
      logtype: apache_error
  - name: lsws_stderror
    file: /host/root/lsws-docker-env/logs/stderr.log
    attributes:
      logtype: apache_error
  - name: auth.log
    file: /host/var/log/auth.log
    attributes:
      logtype: linux_auth
  - name: dpkg.log
    file: /host/var/log/dpkg.10g
    attributes:
      logtype: linux_dpkg
  - name: syslog
    file: /host/var/log/syslog
    attributes:
      logtype: linux_syslog
  - name: containers
    file: /host/var/lib/docker/containers/*/*.log
```

my docker-compose.yml
```
  newrelicinfra:
    build:
      context: containers/newrelic-infra-mysql
    cap_add:
      - SYS_PTRACE
    #network_mode: host
    #pid: host
    hostname: ${HOSTNAME}-jbwww
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
```

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.
