### ISSUE TITLE
msg="can't continue: could not find apache binary"

### ISSUE THREAD

**Issue by simonhoellein** [newrelic/infrastructure-bundle#446]
## Description
When trying to use the apache intetegration I recive the following error message:

```
time="2024-10-17T14:15:33Z" level=error msg="integration log" component=integration-errors env=production fields.level=fatal fields.msg="can't continue: could not find apache binary" integration_name=nri-apache role=nextcloud-1 runner_uid=b5e4add885
```

which looks like the agent can't find the apache binary.

I've did some digging but against my expectation found the apache binary files:

```
d-swcl-1:/# find -name "*apache*"
./var/db/newrelic-infra/newrelic-integrations/bin/nri-apache
./var/db/newrelic-infra/newrelic-integrations/apache-definition.yml
```

## Your Environment
Linux Ubuntu server running latest docker version and the newrelic/infrastructure-bundle:latest in docker with docker-compose

compose-file:

name: newrelic-prod-1

```
services:
  newrelic-infra-bundle:
    hostname: d-swcl-1
    image: newrelic/infrastructure-bundle:latest
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/newrelic-infra:/etc/newrelic-infra:ro
      - ./conf/newrelic-infra.yml:/etc/newrelic-infra.yml:ro
    pid: host
    cap_add:
      - SYS_PTRACE
    privileged: true
    restart: unless-stopped
    environment:
      - NRIA_LICENSE_KEY=eu01x*******************************
    networks:
      - ************
      - *******
      - **************

networks:
  ************:
    external:
      true
  *******:
    external:
      true
  **************:
    external:
      true
```
