### ISSUE TITLE
[REQ] nri-docker to bundle

### ISSUE THREAD

**Issue by MarkG-IEL** [newrelic/infrastructure-bundle#80]
## Is your feature request related to a problem? Please describe.
When using infrastructure-bundle in a Docker environment (for example, to instrument a Docker Compose stack), no Docker metrics or events are created.

## Feature Description
Add nri-docker to the list of packages to be downloaded in bundle.yml

## Additional context
While adding the infrastructure agent directly to a compose file will create the Docker events and metrics that show up in Infrastructure, using this image will not enable Docker integration

## Priority
Really Want

Example docker-compose.yml snippet:
```
  newrelic-agent:
    env_file:
      - ./.env
    container_name: newrelic-infra
    image: newrelic/infrastructure-bundle:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/newrelic-infra:/etc/newrelic-infra:ro
      - ./etc/nginx/nginx.nginx:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
```

**Comment by gsanchezgavier** [comment]
@MarkG-IEL I was just doing some tests here and you might be are overwritten the default config in the image that makes the docker integration work, with mounting this `./etc/newrelic-infra:/etc/newrelic-infra:ro`
```
➜  ~  docker run -it newrelic/infrastructure-bundle:latest sh
/ # cat /etc/newrelic-infra/integrations.d/docker-config.yml
integrations:
  - name: nri-docker
    when:
      feature: docker_enabled
      file_exists: /var/run/docker.sock
    interval: 15s
  - name: nri-docker
    when:
      feature: docker_enabled
      env_exists:
        FARGATE: "true"
    interval: 15s
/ #

```
